spring:
  profiles:
    active: @activatedProperties@

jpa:
  hibernate:
    ddl-auto: none
  show-sql: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
#  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false
#    time-zone: UTC
logging:
  level:
    root: info
    org.springframework.web: error
    com.araica.webapirifas: error
    org.hibernate: error


cors:
  allowedOrings: '*'

application:
  name: @project.artifactId@

build:
  version: @project.version@
  timestamp: @timestamp@
# Bandera que indica si las contraseñas del usuario se cifraran
cypher:
  enabled: false