spring:
  datasource:
#    url: jdbc:mysql://ec2-18-223-118-244.us-east-2.compute.amazonaws.com/rifas?autoReconnect=true
#    username: usr_rifas
#    password: rifas%123'
    url: jdbc:mysql://FLASH-SERVER/premios-dia?autoReconnect=true
    username: web-api-prestamos
    password: 2&(pMe@a<um(F]<)

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false
#    time-zone: UTC
logging:
  level:
    root: info
    org.springframework.web: error
    com.araica.webapirifas: error
    org.hibernate: error


cors:
  allowedOrings: '*'

application:
  name: @project.artifactId@

build:
  version: @project.version@
  timestamp: @timestamp@
# Bandera que indica si las contraseñas del usuario se cifraran
cypher:
  enabled: false
