spring:
  datasource:
    url: jdbc:mysql://ec2-18-216-46-155.us-east-2.compute.amazonaws.com/prestamos_dias_bak_20220622?autoReconnect=true
    username: web-api-prestamos
    password: 2&(pMe@a<um(F]<)